<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\RedShirt.Adventure.Realm.Character.ActionBar.Core\RedShirt.Adventure.Realm.Character.ActionBar.Core.csproj" />
      <ProjectReference Include="..\RedShirt.Adventure.Realm.Common.Database\RedShirt.Adventure.Realm.Common.Database.csproj" />
      <ProjectReference Include="..\RedShirt.Adventure.Realm.Common.Exceptions\RedShirt.Adventure.Realm.Common.Exceptions.csproj" />
    </ItemGroup>

</Project>
